const today = new Date();
const isoAfter = (days) => {
  const date = new Date(today);
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
};

export const seedWorkspace = {
  clients: [
    {
      id: "sementes-do-sul",
      name: "Sementes do Sul",
      sortOrder: 1,
      segment: "Agronegócio",
      status: "Ativo",
      channels: ["Instagram", "LinkedIn"],
      responsibleName: "Patricia",
      responsibleEmail: "patricia@dg5.com.br",
      notes: "Conteúdo técnico e comercial com foco em autoridade, safra e conversão consultiva.",
      brandHealth: 84,
    },
    {
      id: "metodo-facil",
      name: "Método Fácil",
      sortOrder: 2,
      segment: "Educação",
      status: "Ativo",
      channels: ["Instagram", "Facebook"],
      responsibleName: "Equipe DG5",
      responsibleEmail: "patricia@dg5.com.br",
      notes: "Comunicação acolhedora, objetiva e orientada a famílias.",
      brandHealth: 76,
    },
  ],
  brandBrains: [
    {
      id: "sementes-do-sul",
      clientId: "sementes-do-sul",
      status: "Aprovado",
      tone: "Técnico, seguro, próximo e direto. Explicar sem infantilizar.",
      positioning: "Parceira técnica do produtor para decisões de maior produtividade.",
      audience: "Produtores rurais, gestores de fazenda e influenciadores técnicos do agronegócio.",
      preferences: "Dados aplicáveis, exemplos de campo, linguagem clara e chamadas objetivas.",
      restrictions: "Evitar promessas absolutas, jargão sem contexto e tom promocional excessivo.",
      bannedWords: "imperdivel, garantia, milagroso",
      qualityCriteria: "Utilidade prática, rigor técnico, clareza e aderência ao momento da safra.",
      strategicSummary: "A marca deve transformar conhecimento técnico em decisões seguras, aproximando especialista e produtor.",
      learnings: "Conteúdos com contexto regional e aplicação prática recebem melhor retorno.",
      version: 3,
    },
    {
      id: "metodo-facil",
      clientId: "metodo-facil",
      status: "Em revisão",
      tone: "Acolhedor, simples e encorajador.",
      positioning: "Método de ensino que respeita o ritmo de cada aluno.",
      audience: "Famílias com crianças em fase escolar.",
      preferences: "Exemplos cotidianos, mensagens curtas e foco no desenvolvimento.",
      restrictions: "Evitar diagnósticos, comparações entre crianças e promessas de resultado.",
      bannedWords: "cura, garantia, atraso",
      qualityCriteria: "Empatia, clareza e respeito ao desenvolvimento individual.",
      strategicSummary: "Ensino claro e humano para construir autonomia e confiança.",
      learnings: "",
      version: 1,
    },
  ],
  plannedContents: [
    {
      id: "safra-tecnologia",
      clientId: "sementes-do-sul",
      title: "Tecnologia que acompanha a safra",
      channel: "Instagram",
      format: "Carrossel",
      objective: "Reforçar autoridade técnica",
      publishDate: isoAfter(0),
      priority: "Alta",
      status: "Texto em revisão",
      responsibleName: "Patricia",
      responsibleEmail: "patricia@dg5.com.br",
      requiresMetaScheduling: true,
      metaScheduled: false,
      campaign: "Safra 26/27",
      editorialLine: "Tecnologia no campo",
    },
    {
      id: "manejo-na-pratica",
      clientId: "sementes-do-sul",
      title: "Manejo na prática: três decisões",
      channel: "LinkedIn",
      format: "Artigo",
      objective: "Educar e gerar autoridade",
      publishDate: isoAfter(3),
      priority: "Normal",
      status: "Em produção",
      responsibleName: "Equipe DG5",
      responsibleEmail: "patricia@dg5.com.br",
      requiresMetaScheduling: false,
      metaScheduled: false,
      campaign: "Safra 26/27",
      editorialLine: "Conhecimento técnico",
    },
    {
      id: "autonomia-aprendizado",
      clientId: "metodo-facil",
      title: "Autonomia se constrói todos os dias",
      channel: "Instagram",
      format: "Feed",
      objective: "Aproximar famílias",
      publishDate: isoAfter(5),
      priority: "Normal",
      status: "Briefing",
      responsibleName: "Equipe DG5",
      responsibleEmail: "patricia@dg5.com.br",
      requiresMetaScheduling: true,
      metaScheduled: false,
      campaign: "Volta as aulas",
      editorialLine: "Desenvolvimento",
    },
  ],
  contents: [
    {
      id: "safra-tecnologia",
      clientId: "sementes-do-sul",
      plannedContentId: "safra-tecnologia",
      title: "Tecnologia que acompanha a safra",
      channel: "Instagram",
      format: "Carrossel",
      text: "Cada decisão da safra pede informação confiável. Da escolha do material ao acompanhamento no campo, tecnologia só faz sentido quando ajuda o produtor a decidir melhor. Arraste para conhecer três pontos que merecem atenção antes do próximo ciclo.",
      artSuggestion: "Carrossel técnico de cinco telas. Capa com título curto, fotografia real de campo, dados em destaque e hierarquia limpa. Evitar excesso de elementos e imagens artificiais.",
      status: "Texto em revisão",
      origin: "IA + operador",
      fitState: "Ajustes leves",
      guidance: ["Especificar a região ou etapa da safra.", "Trocar uma frase genérica por um dado do planejamento."],
      updatedAt: new Date().toISOString(),
    },
  ],
  notifications: [],
  creativeReviews: [],
  approvals: [],
};
